### ISSUE TITLE
Missing locale file with current gem version

### ISSUE THREAD

**Issue by ryanswood** [castle/devise_castle#2]
STR:
1. Add gem to gemfile and then `bundle`
2. `rails generate devise_castle:install YOUR-API-SECRET`

Error:
> insert  config/initializers/devise.rb
> Could not find "../../../config/locales/en.yml" in any of your source paths. Your current source paths are:
> /Users/woody/src/able/vendor/bundle/ruby/2.3.0/gems/devise_castle-1.3.1/lib/generators/templates

I opened the locally installed gem and indeed did not find the `config/locales/en.yml` file. However, installing the gem from master worked since the locale file was present.

**Comment by brissmyr** [comment]
@ryanswood Thanks for reporting. I'll have a look right away!

**Comment by brissmyr** [comment]
@ryanswood This should now be fixed. Try fetching version 1.3.2 from Rubygems!

**Comment by ryanswood** [comment]
@brissmyr Works! Thanks for the quick turn-around.

**Comment by brissmyr** [comment]
Awesome!
